server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: false
      timeout: 7d

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vkr
    username: klows
    password: 190485
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
